site_name: PCMD
nav:
    - Overview: 'index.md'
    - User Guide: 'user_guide.md'
    - Examples: 'examples.md'
    - Design and Inspiration: 'design.md'
    - Development - Contributing: 'dev.md'
    - Releases: 'releases.md'

extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: '../logo.svg'
  favicon: ../logo.svg
  palette:
    scheme: slate
    primary: cyan
    accent: cyan
  features:
    - navigation.instant
    - header.autohide


plugins:
  - search
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/j0fiN/
    - icon: fontawesome/regular/user
      link: https://jofin-f-archbald.herokuapp.com/
    - icon: octicons/mail-16
      link: mailto:jofinfab@gmail.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jofin-f-archbald-6892b2186/
copyright: Copyright &copy; 2021 Jofin F Archbald
repo_url: https://github.com/j0fiN/pcmd
repo_name: j0fiN/pcmd

markdown_extensions:
  - pymdownx.details
  - def_list
  - pymdownx.highlight
  - codehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true